/*
 * lrGL2DShader.h
 *
 *  Created on: Jan 22, 2017
 *      Author: sereslorant
 */

#ifndef LGLRENDERER_LGL3RENDERER_LGL3SHADERS_LRGL2DSHADER_H_
#define LGLRENDERER_LGL3RENDERER_LGL3SHADERS_LRGL2DSHADER_H_





#endif /* LGLRENDERER_LGL3RENDERER_LGL3SHADERS_LRGL2DSHADER_H_ */
